-- ============================================
-- ТАБЛИЦА: Clients (Клиенты)
-- ============================================
CREATE TABLE clients (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fio_client VARCHAR2(200) NOT NULL,
    phone VARCHAR2(20),
    email VARCHAR2(100) UNIQUE,
    passport_data VARCHAR2(500),
    registration_date DATE DEFAULT SYSDATE
);

-- ============================================
-- ТАБЛИЦА: ConstructionObjects (Объекты)
-- ============================================
CREATE TABLE construction_objects (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_address VARCHAR2(500) NOT NULL,
    object_type VARCHAR2(100) CHECK (object_type IN ('residential','commercial','industrial','infrastructure')),
    square DECIMAL(10,2) CHECK (square > 0),
    floors INTEGER CHECK (floors > 0),
    construction_year INTEGER CHECK (construction_year BETWEEN 1900 AND 2100),
    id_client NUMBER(10) NOT NULL,
    CONSTRAINT fk_obj_client FOREIGN KEY (id_client) REFERENCES clients(id) ON DELETE CASCADE
);

-- ============================================
-- ТАБЛИЦА: Sectors (Сектора)
-- ============================================
CREATE TABLE sectors (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sector_name VARCHAR2(100) NOT NULL UNIQUE,
    description VARCHAR2(500)
);

-- ============================================
-- ТАБЛИЦА: Employees (Сотрудники)
-- ============================================
CREATE TABLE employees (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fio_employee VARCHAR2(200) NOT NULL,
    phone VARCHAR2(20),
    email VARCHAR2(100) UNIQUE,
    id_sector NUMBER(10) NOT NULL,
    position VARCHAR2(100),
    hire_date DATE DEFAULT SYSDATE,
    salary DECIMAL(10,2) CHECK (salary > 0),
    CONSTRAINT fk_emp_sector FOREIGN KEY (id_sector) REFERENCES sectors(id) ON DELETE SET NULL
);

-- ============================================
-- ТАБЛИЦА: SectorHeads (Руководители секторов)
-- ============================================
CREATE TABLE sector_heads (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_sector NUMBER(10) NOT NULL UNIQUE,
    fio_sector_head VARCHAR2(200) NOT NULL,
    phone VARCHAR2(20),
    email VARCHAR2(100) UNIQUE,
    hire_date DATE DEFAULT SYSDATE,
    CONSTRAINT fk_head_sector FOREIGN KEY (id_sector) REFERENCES sectors(id) ON DELETE CASCADE
);

-- ============================================
-- ТАБЛИЦА: Services (Услуги)
-- ============================================
CREATE TABLE services (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_name VARCHAR2(200) NOT NULL UNIQUE,
    description VARCHAR2(500),
    duration_days INTEGER CHECK (duration_days > 0)
);

-- ============================================
-- ТАБЛИЦА: Pricing (Цены)
-- ============================================
CREATE TABLE pricing (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_service NUMBER(10) NOT NULL,
    price DECIMAL(10,2) NOT NULL CHECK (price > 0),
    valid_from DATE DEFAULT SYSDATE NOT NULL,
    valid_to DATE,
    currency VARCHAR2(3) DEFAULT 'RUB' CHECK (currency IN ('RUB','USD','EUR')),
    CONSTRAINT fk_price_service FOREIGN KEY (id_service) REFERENCES services(id) ON DELETE CASCADE
);

-- ============================================
-- ТАБЛИЦА: Contracts (Контракты)
-- ============================================
CREATE TABLE contracts (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_object NUMBER(10) NOT NULL,
    id_client NUMBER(10) NOT NULL,
    contract_number VARCHAR2(50) UNIQUE NOT NULL,
    contract_date DATE DEFAULT SYSDATE NOT NULL,
    total_amount DECIMAL(12,2) CHECK (total_amount >= 0),
    status VARCHAR2(50) DEFAULT 'active' CHECK (status IN ('active','completed','cancelled','pending')),
    id_employee NUMBER(10) NOT NULL,
    CONSTRAINT fk_cont_object FOREIGN KEY (id_object) REFERENCES construction_objects(id) ON DELETE CASCADE,
    CONSTRAINT fk_cont_client FOREIGN KEY (id_client) REFERENCES clients(id) ON DELETE CASCADE,
    CONSTRAINT fk_cont_employee FOREIGN KEY (id_employee) REFERENCES employees(id) ON DELETE SET NULL
);

-- ============================================
-- ТАБЛИЦА: ContractServices (Услуги в контракте)
-- ============================================
CREATE TABLE contract_services (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_service NUMBER(10) NOT NULL,
    id_contract NUMBER(10) NOT NULL,
    id_pricing NUMBER(10) NOT NULL,
    quantity INTEGER DEFAULT 1 CHECK (quantity > 0),
    CONSTRAINT fk_cs_service FOREIGN KEY (id_service) REFERENCES services(id) ON DELETE CASCADE,
    CONSTRAINT fk_cs_contract FOREIGN KEY (id_contract) REFERENCES contracts(id) ON DELETE CASCADE,
    CONSTRAINT fk_cs_pricing FOREIGN KEY (id_pricing) REFERENCES pricing(id) ON DELETE RESTRICT,
    CONSTRAINT uk_contract_service UNIQUE (id_contract, id_service, id_pricing)
);

-- ============================================
-- ТАБЛИЦА: Payments (Платежи)
-- ============================================
CREATE TABLE payments (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_date DATE DEFAULT SYSDATE NOT NULL,
    amount DECIMAL(10,2) NOT NULL CHECK (amount > 0),
    payment_method VARCHAR2(50) CHECK (payment_method IN ('cash','bank_transfer','card','online')),
    status VARCHAR2(50) DEFAULT 'pending' CHECK (status IN ('pending','completed','failed','refunded')),
    id_contract NUMBER(10) NOT NULL,
    CONSTRAINT fk_pay_contract FOREIGN KEY (id_contract) REFERENCES contracts(id) ON DELETE CASCADE
);

-- ============================================
-- ТАБЛИЦА: Documents (Документы)
-- ============================================
CREATE TABLE documents (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_contract NUMBER(10) NOT NULL,
    document_name VARCHAR2(200) NOT NULL,
    document_type VARCHAR2(100) CHECK (document_type IN ('contract','act','report','certificate','other')),
    upload_date DATE DEFAULT SYSDATE NOT NULL,
    file_path VARCHAR2(500),
    status VARCHAR2(50) DEFAULT 'uploaded' CHECK (status IN ('uploaded','verified','archived','deleted')),
    CONSTRAINT fk_doc_contract FOREIGN KEY (id_contract) REFERENCES contracts(id) ON DELETE CASCADE
);

-- ============================================
-- ТАБЛИЦА: ExpertiseReports (Отчеты по экспертизе)
-- ============================================
CREATE TABLE expertise_reports (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_contract NUMBER(10) NOT NULL,
    id_employee NUMBER(10) NOT NULL,
    report_number VARCHAR2(50) UNIQUE NOT NULL,
    report_date DATE DEFAULT SYSDATE NOT NULL,
    conclusion VARCHAR2(1000),
    status VARCHAR2(50) DEFAULT 'draft' CHECK (status IN ('draft','in_review','approved','rejected')),
    id_sector_head NUMBER(10) NOT NULL,
    CONSTRAINT fk_exp_contract FOREIGN KEY (id_contract) REFERENCES contracts(id) ON DELETE CASCADE,
    CONSTRAINT fk_exp_employee FOREIGN KEY (id_employee) REFERENCES employees(id) ON DELETE SET NULL,
    CONSTRAINT fk_exp_head FOREIGN KEY (id_sector_head) REFERENCES sector_heads(id) ON DELETE SET NULL
);

-- ============================================
-- ИНДЕКСЫ
-- ============================================
CREATE INDEX idx_contracts_status ON contracts(status);
CREATE INDEX idx_contracts_date ON contracts(contract_date);
CREATE INDEX idx_pricing_valid ON pricing(valid_from, valid_to);
CREATE INDEX idx_pricing_service ON pricing(id_service);
CREATE INDEX idx_expertise_date ON expertise_reports(report_date);
CREATE INDEX idx_expertise_status ON expertise_reports(status);
CREATE INDEX idx_payments_date ON payments(payment_date);
CREATE INDEX idx_payments_status ON payments(status);
CREATE INDEX idx_documents_type ON documents(document_type);
CREATE INDEX idx_employees_sector ON employees(id_sector);

COMMIT;